title: Docker Workshop
description: 工作坊實作記錄
base: /docker-workshop/
dest: dist
themeConfig:
  sidebar:
    - /src/basic
    - /src/build
  repo: ganhuaking/docker-workshop
  repoLabel: GitHub
  editLinks: true
  editLinkText: 編輯這個頁面
